name: Trigger Deployment

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-20.04
    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 35

    steps:
      - uses: actions/checkout@v3.1.0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip --version
          pip install . --upgrade --quiet --find-links https://download.pytorch.org/whl/cpu/torch_stable.html
          pip list
        shell: bash

      - name: Deploy
        env:
          BOT_TOKEN: ${{secrets.BOT_TOKEN}}
          SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
          SIGNING_SECRET: ${{secrets.SIGNING_SECRET}}
          SLACK_CLIENT_ID: ${{secrets.SLACK_CLIENT_ID}}
          CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
          LIGHTNING_USER_ID: ${{secrets.LIGHTNING_USER_ID}}
          LIGHTNING_API_KEY: ${{secrets.LIGHTNING_API_KEY}}
          PACKAGE_LIGHTNING: "1"
        run: |
          lightning run app app.py --cloud \
            --name "Stable Diffusion" \
            --env RATE_LIMIT_KEY=${{secrets.RATE_LIMIT_KEY}} \
            --env SHEET_API_URL=${{secrets.SHEET_API_URL}} \
            --env MUSE_ROOT_PATH="/muse" \
            --env MUSE_ENABLE_ANALYTICS=1 \
            --env MUSE_SYSTEM_PASSWORD="${{secrets.MUSE_SYSTEM_PASSWORD}}"
        shell: bash
